# Site settings
title: Java Blog of mine.
email: krzysztofurman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Basically Java and maybe other JVM languages.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qrman.github.io" # the base hostname & protocol for your site
twitter_username: krzysztof_urman
github_username:  qrman

# Build settings
markdown: kramdown
