# Site settings
title: Java Blog of mine.
email: krzysztofurman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Basically Java and maybe other JVM languages.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qrman.github.io" # the base hostname & protocol for your site
twitter_username: krzysztof_urman
github_username:  qrman

meta_description: >
  Krzysztof Urman's blog about: Java, JVM, Vert.x.

# Build settings
markdown: kramdown

permalink: /posts/:year/:month/:day/:title/

gems: [jekyll-redirect-from]